# Generated by Django 4.2.3 on 2023-08-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.CharField(choices=[('PUBLIC', '공개'), ('PRIVATE', '비밀')], default='PRIVATE', max_length=10)),
                ('emotion', models.CharField(choices=[('JOY', '기쁨'), ('EXCITEMENT', '설렘'), ('SAD', '슬픔'), ('ANGRY', '분노'), ('LONELY', '외로움')], default='JOY', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='diary_thumbnails/')),
            ],
        ),
    ]
